apiVersion : apps/v1
kind: Deployment
metadata:
  name: "troubleshooting-app"
  namespace: troubleshooting
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "troubleshooting-app"
  template:
    metadata:
      labels:
        app: "troubleshooting-app"
    spec:
      tolerations: []
      containers:
        - name: "troubleshooting-app"
          image: cepgbaseacr.azurecr.io/troubleshooting:latest
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
          limits:
              memory: "2Gi"
              cpu: "1000m"
